Repository xmos/lib_xud, pull requests merged in 2021-07, with the labels that each got.

#210 Feature/test_core_freq
  .gitignore
  tests/conftest.py
  tests/helpers.py
  tests/shared_src/test_xs3_600.xn
  tests/shared_src/test_xs3_800.xn
  tests/test_bulk_rx_multiep.py
  tests/test_makefile.mak
  tests/usb_signalling.py
Labels: type:testing

#223 Fix/190
  requirements.txt
  tests/Pyxsim/__init__.py
  tests/conftest.py
  tests/helpers.py
  tests/shared_src/shared.h
  tests/shared_src/test_main.xc
  tests/test_makefile.mak
  tests/usb_phy.py
Labels: type:testing

#226 Fixed args bugs
  tests/conftest.py
  tests/helpers.py
Labels: type:testing

#228 Fix/227
  lib_xud/src/core/included/XUD_Token_Setup_DI.S
  tests/test_control_basic_set.py
  tests/test_stall_control.py
  tests/test_stall_control/Makefile
  tests/test_stall_control/src/main.xc
  tests/usb_session.py
  tests/usb_transaction.py
Labels: type:bug

#232 Fix for #231
  tests/test_control_basic_get.py
  tests/test_control_basic_set.py
Labels: type:testing

#233 Fix/229
  tests/test_bulk_rx_basic/LICENSE.rst
  tests/test_bulk_rx_basic_badcrc32/LICENSE.rst
  tests/test_bulk_rx_basic_badpid/LICENSE.rst
  tests/test_bulk_rx_basic_nodata/LICENSE.rst
  tests/test_bulk_rx_basic_rxerror/LICENSE.rst
  tests/test_bulk_rx_multiep/LICENSE.rst
  tests/test_bulk_rx_traffic/LICENSE.rst
  tests/test_bulk_tx_badack/LICENSE.rst
  tests/test_bulk_tx_basic/LICENSE.rst
  tests/test_bulk_tx_basic_short/LICENSE.rst
  tests/test_bulk_tx_multiep/LICENSE.rst
  tests/test_control_basic_badcrc32/LICENSE.rst
  tests/test_control_basic_get/LICENSE.rst
  tests/test_control_basic_set/LICENSE.rst
  tests/test_control_basic_short/LICENSE.rst
  tests/test_control_repeatedsetup/LICENSE.rst
  tests/test_control_traffic.py
  tests/test_control_traffic/Makefile
  tests/test_control_traffic/src/main.xc
  tests/test_invalidtoken/LICENSE.rst
  tests/test_iso_loopback/LICENSE.rst
  tests/test_iso_rx_basic/LICENSE.rst
  tests/test_iso_rxtx_fastpacket/LICENSE.rst
  tests/test_iso_tx_basic/LICENSE.rst
  tests/test_ping_rx_basic/LICENSE.rst
  tests/test_shorttoken/LICENSE.rst
  tests/test_sof_badcrc/LICENSE.rst
  tests/test_sof_basic/LICENSE.rst
Labels: type:testing

#239 Fix/237
  examples/AN00129_hid_class/Makefile
  lib_xud/src/core/XUD_HAL.xc
Labels: type:cleanup
