Repository xmos/lib_xud, pull requests merged in 2021-06, with the labels that each got.

#171 Remove build warnings
  lib_xud/src/core/XUD_DeviceAttach.xc
  lib_xud/src/core/XUD_HAL.xc
  lib_xud/src/core/XUD_Signalling.xc
Labels: type:cleanup

#140 Issue STALL even when EP is marked ready
  lib_xud/src/core/included/XUD_Token_In_DI.S
  lib_xud/src/core/included/XUD_Token_Out.S
  lib_xud/src/core/included/XUD_Token_Out_DI.S
Labels: type:bug

#175 Remove old app_test dir
  __app_test/.cproject
  __app_test/.project
  __app_test/.xproject
  __app_test/LICENSE.rst
  __app_test/Makefile
  __app_test/README
  __app_test/README.rst
  __app_test/main.xc
Labels: type:cleanup

#178 Remove duplicate hid.h file in AN00129.
  examples/AN00129_hid_class/src/hid.h
Labels: type:cleanup

#176 Feature/test params
  .gitignore
  tests/Pyxsim/testers.py
  tests/Pyxsim/xmostest_subprocess.py
  tests/conftest.py
  tests/helpers.py
  tests/test_bulk_loopback.py
  tests/test_bulk_rx_basic.py
  tests/test_bulk_rx_basic_badcrc32.py
  tests/test_bulk_rx_basic_badpid.py
  tests/test_bulk_rx_basic_nodata.py
  tests/test_bulk_rx_basic_rxerror.py
  tests/test_bulk_rx_multiep.py
  tests/test_bulk_rx_traffic.py
  tests/test_bulk_tx_badack.py
  tests/test_bulk_tx_basic.py
  tests/test_bulk_tx_basic_short.py
  tests/test_bulk_tx_multiep.py
  tests/test_bulk_tx_noack.py
  tests/test_control_basic_get.py
  tests/test_control_basic_set.py
  tests/test_device_attach.py
  tests/test_invalidtoken.py
  tests/test_iso_loopback.py
  tests/test_iso_rx_basic.py
  tests/test_iso_rxtx_fastpacket.py
  tests/test_iso_tx_basic.py
  tests/test_ping_rx_basic.py
  tests/test_ping_stall.py
  tests/test_shorttoken.py
  tests/test_sof_badcrc.py
  tests/test_sof_basic.py
  tests/test_stall_basic.py
  tests/test_stall_epready.py
  tests/test_suspend_resume.py
  tests/usb_phy.py
  tests/usb_session.py
Labels: type:testing

#194 Fix to test_sof_basic
  tests/test_sof_basic/src/main.xc
  tests/test_stall_basic/src/main.xc
  tests/test_stall_epready/src/main.xc
Labels: type:testing

#196 Fixed for issue #172 (trap on XS2 device)
  lib_xud/src/core/included/XUD_Token_Out_DI.S
Labels: type:bug

#197 Feature/tidyup
  lib_xud/src/core/XUD_Main.xc
  lib_xud/src/core/XUD_Signalling.h
  lib_xud/src/core/XUD_UIFM_PConfig.S
  lib_xud/src/core/XUD_UIFM_RegAccess.S
  lib_xud/src/core/included/XUD_Token_In.S
  lib_xud/src/core/included/XUD_Token_Out.S
  lib_xud/src/core/included/XUD_Token_Setup.S
  tests/Pyxsim/__init__.py
Labels: type:cleanup
